version: '3.5'
services:
    nexus:
        image: sonatype/nexus3
        volumes:
            - ./../nexus-data/:/nexus-data/:cached
        ports:
            - 8081:8081
    appservice:
        container_name: octogen
        depends_on:
            - nexus
        build:
            context: .
            dockerfile: Dockerfile
            network: host
        volumes:
            - ./../octogen/:/workspace/:delegated
        network_mode: host
        command: /bin/sh -c "while sleep 10; do :; done"
